language: php
php:
  - 5.5
  - 5.6
env:
  - MAGENTO=1.9.1.0
  - MAGENTO=2.0.42.0-beta10
matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: TEST_SUITE=Static
  allow_failures:
    - env: TEST_SUITE=Static
sudo: false
before_install:
  - mkdir test-root/
install:
  - composer install --dev
before_script:
  - php vendor/bin/cotya-setup_travis.php
script:
  - > 
    sh -c "if [ '$TEST_SUITE' = 'Static' ]; then
      ./vendor/bin/phpcs -v --standard=PSR2 --ignore="/test-root|/lib|/shell|/vendor|/m1" ./;
    else
      vendor/bin/phpunit
    fi"
#notifications:
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/5126f06d0f4f55230ee0
#    on_success: change  # options: [always|never|change] default: always
#    on_failure: always  # options: [always|never|change] default: always
#    on_start: false     # default: false
